server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ecommerce_user
    password: mypassword
    url: jdbc:postgresql://localhost:8432/db_order
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
